version: 2.1

orbs: 
  codecov: codecov/codecov@3.2.3
  node: circleci/node@4.7.0
  
jobs:
  build--test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          
      # And finally run the release build
      - run:
          command: ./gradlew jacocoTestReport
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
            
      - codecov/upload
      
workflows:
  TestTest: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build--test
